const mongoose = require('mongoose');

const AccountSchema = mongoose.Schema({
    account_id:{
        type:String,
        required:true
    },
    account_owner:{
        type:String,
        required:true
    },
    company_name:{
        type:String,
        required:true
    },
    industry:{
        type:String,
        required:true
    },

    company_country:{
        type:String,
        required:true
    },
    company_state:{
        type:String,
        required:true
    },
    company_city:{
        type:String,
        required:true
    },
   
    company_location:{
        type:String,
        required:true
    },
    gst:{
        type:String,
        required:true
    },
    pan:{
        type:String,
        required:true
    },
    tan:{
        type:String,
        required:true
    },
    cin:{
        type:String,
        required:true
    },
    country_code:{
        type:String,
        required:true
    },
    phone_no:{
        type:String
    },
    mobile_no:{
        type:String,
        required:true
    },
    email:{
        type:String
    },
    secondary_email:{
        type:String
    },
    address1:{
        type:String,
        required:true
    },
    address2:{
        type:String
    },
    address3:{
        type:String
    },
    country:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    zip_code:{
        type:String,
        required:true
    },
    remark:{
        type:String,
        required:true
    },
    created_at:{
        type:Date,
        required:true
    },
    modified_at:{
        type:Date
    }
})

module.exports = AccountSchema