const mongoose = require('mongoose');


const DealLogSchema=mongoose.Schema({
    deal_id:{
        type:String,
        required:true
    },
    deal_owner:{
        type:String,
        required:true
    },
    deal_source:{
        type:String,
        required:true
    },
    deal_type:{
        type:String,
        required:true
    },
    account_id:{
        type:String,
        required:true
    },
    referral:{
        type:String
    },
    pre_deal_type:{
        type:String,
        required:true
    },
    deal_title:{
        type:String,
        required:true
    },
    product_servises:{
        type:String,
        required:true
    },
    billing_address:{
        type:String
    },
    shipping_address:{
        type:String
    },
    deal_status_stage:{
        type:String,
        required:true
    },
    created_by:{
        type:String,
        required:true
    },
    created_date_time:{
        type:Date,
        required:true
    },
    modified_by:{
        type:String,
        required:true
    },
    modified_date_time:{
        type:Date,
        required:true
    },
    notes:{
        type:String
    },
    attachments:{
        type:String
    },
    terms_condition:{
        type:String,
        required:true
    },
    edit_status:{
        type:Boolean,
        required:true
    },
})

module.exports=DealLogSchema