const mongoose =require("mongoose")
const DisposalSchema=mongoose.Schema({
    disposal_id:{
        type:String
    },
    company_type:{
        type:String
    },
    user_id:{
        type:String
    },
    disposal_company_name:{
        type:String
    },
    disposal_state:{
        type:String
    },
    disposal_city:{
        type:String
    },
    plant_name:{
        type:String
    },
    alias_name:{
        type:String
    },
    gstin:{
        type:String
    },
    address:{
        type:String
    },
    state:{
        type:String
    },
    city:{
type:String
    },
    latitude:{
        type:String
    },
    longitude:{
        type:String
    },
    town:{
        type:String
    },
    title:{
        type:String
    },
    first_name:{
        type:String
    },
    last_name:{
        type:String
    },
    phone:{
        type:String
    },
    mobile:{
        type:String
    },
    email:{
        type:String
    },
    monthly_qty_mlp:{
        type:String
    },
    population:{
        type:String
    },
    attachments:{
        type:Array
    },
    created_at:{
		type:Date
	},
    updated_at:{
        type:Date
    }
})
const DisposalModel=mongoose.model('epr_disposal',DisposalSchema)
module.exports=DisposalModel