const mongoose =require('mongoose')

const disposalexecutionSchema=mongoose.Schema({
    material_name:{
        type:String
    },
    state:{
        type:String
    },
    city:{
        type:String
    },
    ulb:{
        type:String
    },
    collection_center:{
        type:String
    },
    disposal_facility_pwpf:{
        type:String
    },
    transporter_name:{
        type:String
    },
    mobile_no:{
        type:String
    },
    vehicle_no:{
        type:String
    },
    driver_name:{
        type:String
    },
    driver_mobile_no:{
        type:String
    },
    bill_t_no:{
        type:String
    },
    e_way_bill:{
        type:String
    },
    invoice_no:{
        type:String
    },
    payment:{
    type:Array
    },
    collection_date_time:{
        type:String
    },
    collection_material_weight:{
        type:String
    },
    collection_remark:{
        type:String
    },
    disposal_date_time:{
        type:String
    },
    disposal_material_weight:{
        type:String
    },
    disposal_remark:{
        type:String
    },
    attachments:{
        type:Array
    },
    created_at:{
		type:Date
	},
    updated_at:{
        type:Date
    },
    status:{
        type:Boolean,default:true
    }
})
const DisposalExecutionModel=mongoose.model('epr_disposalexecution',disposalexecutionSchema)
module.exports=DisposalExecutionModel