const mongoose =require('mongoose')

const roleSchema = mongoose.Schema({
  role_name: String,
  description: String,
  customerview: { type:Boolean, default: false },
  customercreate: { type:Boolean, default: false },
  customeredit: { type:Boolean, default: false },
  customerdelete: { type:Boolean, default: false },
//   leadverifier: { type:Boolean, default: false },
//   leadapprover: { type:Boolean, default: false },
ulbview: { type:Boolean, default: false },
ulbcreate: { type:Boolean, default: false },
ulbedit: { type:Boolean, default: false },
ulbdelete: { type:Boolean, default: false },
//   quoteverifier: { type:Boolean, default: false },
//   quoteapprover: { type:Boolean, default: false },
collectioncenterview: { type:Boolean, default: false },
collectioncentercreate: { type:Boolean, default: false },
collectioncenteredit: { type:Boolean, default: false },
collectioncenterdelete: { type:Boolean, default: false },
//   dealverifier: { type:Boolean, default: false },
//   dealapprover: { type:Boolean, default: false },
transporterview: { type:Boolean, default: false },
transportercreate: { type:Boolean, default: false },
transporteredit: { type:Boolean, default: false },
transporterdelete: { type:Boolean, default: false },
disposalview: { type:Boolean, default: false },
disposalcreate: { type:Boolean, default: false },
disposaledit: { type:Boolean, default: false },
disposaldelete: { type:Boolean, default: false },
  userview: { type:Boolean, default: false },
  usercreate: { type:Boolean, default: false },
  useredit: { type:Boolean, default: false },
  userdelete: { type:Boolean, default: false },
  roleview: { type:Boolean, default: false },
  rolecreate: { type:Boolean, default: false },
  roleedit: { type:Boolean, default: false },
  roledelete: { type:Boolean, default: false },
  order_op: { type:Boolean, default: false },
  target: { type:Boolean, default: false },
  collection_disposal_execution: { type:Boolean, default: false },
//   convertleadtoquote: { type:Boolean, default: false },
//   convertquotetodeal: { type:Boolean, default: false },
});
const RoleModal=mongoose.model('epr_role',roleSchema)
module.exports = RoleModal;


