const mongoose = require("mongoose");

const roleSchema = mongoose.Schema({
  role_name: String,
  description: String,
  leadview: { type: Boolean, default: false },
  leadcreate: { type: Boolean, default: false },
  leadedit: { type: Boolean, default: false },
  leaddelete: { type: Boolean, default: false },
  leadverifier: { type: Boolean, default: false },
  leadapprover: { type: Boolean, default: false },
  quoteview: { type: Boolean, default: false },
  quotecreate: { type: Boolean, default: false },
  quoteedit: { type: Boolean, default: false },
  quotedelete: { type: Boolean, default: false },
  quoteverifier: { type: Boolean, default: false },
  quoteapprover: { type: Boolean, default: false },
  dealview: { type: Boolean, default: false },
  dealcreate: { type: Boolean, default: false },
  dealedit: { type: Boolean, default: false },
  dealdelete: { type: Boolean, default: false },
  dealverifier: { type: Boolean, default: false },
  dealapprover: { type: Boolean, default: false },
  accountview: { type: Boolean, default: false },
  accountcreate: { type: Boolean, default: false },
  accountedit: { type: Boolean, default: false },
  accountdelete: { type: Boolean, default: false },
  contactview: { type: Boolean, default: false },
  contactcreate: { type: Boolean, default: false },
  contactedit: { type: Boolean, default: false },
  contactdelete: { type: Boolean, default: false },
  userview: { type: Boolean, default: false },
  usercreate: { type: Boolean, default: false },
  useredit: { type: Boolean, default: false },
  userdelete: { type: Boolean, default: false },
  roleview: { type: Boolean, default: false },
  rolecreate: { type: Boolean, default: false },
  roleedit: { type: Boolean, default: false },
  roledelete: { type: Boolean, default: false },
  convertleadtoquote: { type: Boolean, default: false },
  convertquotetodeal: { type: Boolean, default: false },
});
const RoleModal=mongoose.model('dt_role',roleSchema)
module.exports = RoleModal;
